### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by strk** [mikeshultz/xsd2pgsql#6]
Getting an error trying to convert http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Ar5/4.6/FKB-Ar546.xsd
```
$ xsd2pgsql/xsd2pgsql.py FKB-Ar546.xsd
Traceback (most recent call last):
  File "xsd2pgsql/xsd2pgsql.py", line 258, in <module>
    buildTypes(XMLS, xsd)
  File "xsd2pgsql/xsd2pgsql.py", line 165, in buildTypes
    USER_TYPES[pg_normalize(el.get('name'))] = restr.get('base').replace(XMLS_PREFIX, '')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by jussico** [comment]
same error with https://www.loc.gov/standards/alto/v3/alto-3-0.xsd

any ideas how to fix this by either modifying the .xsd a bit or fixing the code?

**Comment by runegitar** [comment]
Same here with http://skjema.geonorge.no/SOSI/produktspesifikasjon/Norskvann-Asbuilt/2.2/Asbuilt.xsd

**Comment by runegitar** [comment]
solved my problem when i edited the function call to buildTypes like shown under:
           
# glean out defined types
            buildTypes(XMLS, xsd)

**Comment by runegitar** [comment]
I had the same problem with http://skjema.geonorge.no/SOSI/produktspesifikasjon/Norskvann-Asbuilt/2.2/Asbuilt.xsd 
Setting **buildTypes('', xsd)** solved the problem, for both asbuilt.xsd and FKB-Ar546.xsd, but many of the attributes are missing from the tables.
